apiVersion: v1
kind: Service
metadata:
  name: myapp-bad
  namespace: bookinfo
spec:
  selector:
    app: myapp-bad
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-bad
  namespace: bookinfo
  labels:
    app: myapp-bad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-bad
  template:
    metadata:
      labels:
        app: myapp-bad
    spec:
      tolerations:
        - key: spot
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/capacityType
                    operator: In
                    values: ["SPOT"]
      containers:
        - name: myapp
          image: 334734167946.dkr.ecr.ap-southeast-3.amazonaws.com/myapp-bad:latest
          ports:
            - containerPort: 8080
